config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :motors

  get 'archive', to: 'archive#index', as: 'archive'
  direct 'docs_archive' do
    'https://aiiot.ssu.ac.kr/docs/pat/'
  end

  get 'tracking(/:page)', to: 'tracking#index', as: 'tracking'
  direct 'streamlit' do
    # "https://aiiot.ssu.ac.kr/streamlit/tracking"
    if Rails.env == 'development'
      'http://localhost:8501/'
    else
      'https://aiiot.ssu.ac.kr/streamlit/'
    end
  end

  direct :zoolu do
    if Rails.env == 'development'
      'http://localhost:3000'
    else
      'https://zoolu.co.kr'
    end
  end

  # Defines the root path route ("/")
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/motor.rb
class Motor < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/archive_controller.rb
class ArchiveController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/motors_controller.rb
class MotorsController < ApplicationController
  before_action :set_motor, only: %i[ show edit update destroy ]

  # GET /motors or /motors.json
  def index
    @motors = Motor.all
  end

  # GET /motors/1 or /motors/1.json
  def show
  end

  # GET /motors/new
  def new
    @motor = Motor.new
  end

  # GET /motors/1/edit
  def edit
  end

  # POST /motors or /motors.json
  def create
    @motor = Motor.new(motor_params)

    respond_to do |format|
      if @motor.save
        format.html { redirect_to motor_url(@motor), notice: "Motor was successfully created." }
        format.json { render :show, status: :created, location: @motor }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @motor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /motors/1 or /motors/1.json
  def update
    respond_to do |format|
      if @motor.update(motor_params)
        format.html { redirect_to motor_url(@motor), notice: "Motor was successfully updated." }
        format.json { render :show, status: :ok, location: @motor }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @motor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /motors/1 or /motors/1.json
  def destroy
    @motor.destroy

    respond_to do |format|
      format.html { redirect_to motors_url, notice: "Motor was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_motor
      @motor = Motor.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def motor_params
      params.require(:motor).permit(:title, :content)
    end
end

app/controllers/tracking_controller.rb
class TrackingController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/archive_helper.rb
module ArchiveHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/motors_helper.rb
module MotorsHelper
end

app/helpers/tracking_helper.rb
module TrackingHelper
end

app/views/archive/index.html.erb
<div class='iframed'>
  <%# <iframe src="http://localhost:8000/" frameborder="0" width='100%'></iframe> %>
  <iframe src=<%= docs_archive_url %> frameborder="0" width='100%'>
  </iframe>
</div>

app/views/home/index.html.erb
<div class='home'>
  <article>
    <h1 class='text-center text-4xl my-16'>방문을 환영합니다</h1>

    <p class='my-12'>
    AI IoT LAB 에서는 딥러닝 기반의 영상 추적과 모터 제어 솔루션을 연구합니다.
    </p>

    <ul>
      <li>
        Yolo 와 OpenCV 를 활용한 영상 추적 데모를 보려면 <%= link_to('여기', tracking_path) %> 를 클릭하세요. 
      </li>
      <li>
        모터 콘트롤에 대한 정보를 보려면 <%= link_to('여기', motors_path) %> 를 클릭하세요. 
      </li>

      <li>
        문서 아카이브를 방문한 학생은 <%= link_to('여기', archive_path) %> 를 클릭하세요.
      </li>
    </ul>
  </article>  
</div>

app/views/layouts/_flash.html.erb
<div class="flash flex flex-row justify-between items-center" data-controller='flash' data-flash-target='element'>
  <div class='w-1/12 xxborder xxborder-solid'></div>

  <div class='flex justify-center xxborder xxborder-solid'>
    <span class='text-green-600'>
      <%= msg %>
    </span>

  </div>

  <div class='w-1/12 flex justify-center xxborder xxborder-solid'>
    <span class='text-green-600 cursor-pointer' data-action="click->flash#close">
      <i class="fa-regular fa-circle-xmark"></i>
      <%# <i class="fa fa-times-circle"></i> %>
    </span>    
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer>
  <p>AIIOT LAB &copy; 2023</p>
</footer>

app/views/layouts/_header.html.erb
<header>
  <h1 class=''>AI IoT LAB</h1>
  <p class=''>Object Tracking and Motor Control powered by Deep Learning</p>
  <nav>
    <ul>
      <li><a class='' href="/">소개</a></li>
      <li><a class='' href="/tracking">오브젝트 트래킹</a></li>
      <li><a class='' href="/motors">모터 제어</a></li>
      <li><a class='' href="/archive">문서 아카이브</a></li>
    </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AIIOT LAB</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%#= render 'layouts/flash', name: 'notice', msg: 'xxx xxx xxxxx xxxxxx xxxxxxxx' %>
    <% flash.each do |name, msg| %>
      <%= render 'layouts/flash', name: name, msg: msg %>
    <% end %>

    <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/motors/_form.html.erb
<%= form_with(model: motor) do |form| %>
  <% if motor.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(motor.errors.count, "error") %> prohibited this motor from being saved:</h2>

      <ul>
        <% motor.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_field :content %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/motors/_motor.html.erb
<div id="<%= dom_id motor %>">
  <p>
    <strong>Title:</strong>
    <%= motor.title %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= motor.content %>
  </p>

</div>

app/views/motors/edit.html.erb
<h1>Editing motor</h1>

<%= render "form", motor: @motor %>

<br>

<div>
  <%= link_to "Show this motor", @motor %> |
  <%= link_to "Back to motors", motors_path %>
</div>

app/views/motors/index.html.erb
<p class="notice text-center bg-orange-100">
  준비 중입니다. 
</p>

<div class='text-center'>
  <%= link_to "돌아가기", root_path, class: 'text-sm underline' %>
</div>

app/views/motors/new.html.erb
<h1>New motor</h1>

<%= render "form", motor: @motor %>

<br>

<div>
  <%= link_to "Back to motors", motors_path %>
</div>

app/views/motors/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @motor %>

<div>
  <%= link_to "Edit this motor", edit_motor_path(@motor) %> |
  <%= link_to "Back to motors", motors_path %>

  <%= button_to "Destroy this motor", @motor, method: :delete %>
</div>

app/views/tracking/index.html.erb
<div class='iframed'>
  <!--
  <iframe src='https://127.0.0.1:8501/tracking/<%= params[:page] %>' frameborder="0" width='100%'>
  <iframe src='https://127.0.0.1:8501/tracking/<%= params[:page] %>' frameborder="0" width='100%'>
  -->
  <iframe src=<%= streamlit_url %> frameborder="0" width='100%'></iframe>
</div>